<?php
/**
 * patient/generate_disability_pdf.php
 * Generates + downloads the official ApexCare Disability Assessment PDF.
 * Saves to pdf_reports/ and caches the path in disability_assessments.pdf_path.
 */

session_start();
require_once '../db.php';

/* AUTH */
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'patient') {
    header('Location: login.php'); exit();
}

$patient_id    = (int)$_SESSION['user_id'];
$assessment_id = (int)($_GET['id'] ?? 0);
if ($assessment_id < 1) { http_response_code(400); exit('Invalid request.'); }

/* FETCH */
$stmt = $conn->prepare("
    SELECT da.*,
           mc.condition_name,
           mc.category                             AS condition_category,
           CONCAT(u.first_name, ' ', u.last_name)  AS doctor_name,
           dp.specialization                       AS doctor_specialization,
           pat.first_name  AS patient_first,
           pat.last_name   AS patient_last,
           pat.national_id, pat.date_of_birth,
           pat.gender, pat.phone, pat.email
    FROM   disability_assessments da
    JOIN   medical_conditions mc  ON mc.id        = da.condition_id
    JOIN   users u                ON u.id         = da.doctor_id
    LEFT JOIN doctor_profiles dp  ON dp.doctor_id = da.doctor_id
    JOIN   users pat              ON pat.id       = da.patient_id
    WHERE  da.id = :aid AND da.patient_id = :pid
");
$stmt->execute([':aid' => $assessment_id, ':pid' => $patient_id]);
$a = $stmt->fetch(PDO::FETCH_ASSOC);
if (!$a) { http_response_code(404); exit('Assessment not found.'); }

/* LOAD FPDF */
require_once __DIR__ . '/../fpdf/fpdf.php';


/* HELPERS */
function safe(mixed $v, string $fb = 'N/A'): string {
    return ($v !== null && trim((string)$v) !== '') ? trim((string)$v) : $fb;
}
function calcAge(string $dob): string {
    try { return (string)(int)(new DateTime($dob))->diff(new DateTime())->y; }
    catch (Exception) { return 'N/A'; }
}

/* COLOURS */
define('NR',11);  define('NG',39);  define('NB',64);   // navy
define('TR',26);  define('TG',158); define('TB',154);  // teal
define('GR',201); define('GG',168); define('GB',76);   // gold
define('SR',240); define('SG',247); define('SB',250);  // surface
define('MR',100); define('MG',116); define('MB',139);  // muted
define('DR',15);  define('DG',23);  define('DB',42);   // dark text
define('WR',255); define('WG',255); define('WB',255);  // white

/* PDF CLASS */
class DisabilityReport extends FPDF {

    public function Header(): void {
        $this->SetFillColor(NR,NG,NB); $this->Rect(0,0,210,22,'F');
        $this->SetFillColor(TR,TG,TB); $this->Rect(0,22,210,2,'F');
        $this->SetFillColor(GR,GG,GB); $this->Rect(0,24,210,1,'F');
        $this->SetFont('Arial','B',16);
        $this->SetTextColor(WR,WG,WB);
        $this->SetXY(10,5); $this->Cell(55,8,'APEXCARE',0,0,'L');
        $this->SetFont('Arial','',9);
        $this->SetTextColor(180,210,225);
        $this->SetXY(65,7); $this->Cell(0,6,'Medical Assessment Report for Persons with Disabilities',0,0,'C');
        $this->SetFont('Arial','',8);
        $this->SetTextColor(160,190,210);
        $this->SetXY(160,7); $this->Cell(40,6,'Page '.$this->PageNo(),0,0,'R');
        $this->SetY(30); $this->SetTextColor(DR,DG,DB);
    }

    public function Footer(): void {
        $this->SetY(-15);
        $this->SetFillColor(SR,SG,SB); $this->Rect(0,$this->GetY(),210,15,'F');
        $this->SetFont('Arial','I',7.5); $this->SetTextColor(MR,MG,MB);
        $this->Cell(0,5,'This report is electronically generated by ApexCare Health Management System and is valid only when verified by the issuing health facility.',0,1,'C');
        $this->Cell(0,5,'ApexCare  |  Generated: '.date('d M Y, H:i'),0,0,'C');
    }

    public function sectionBar(string $t): void {
        $this->SetFillColor(NR,NG,NB); $this->SetTextColor(WR,WG,WB);
        $this->SetFont('Arial','B',9);
        $this->Cell(0,7,'  '.strtoupper($t),0,1,'L',true);
        $this->SetTextColor(DR,DG,DB); $this->Ln(1);
    }

    public function dataRow(string $label, string $val, float $lw=52): void {
        $this->SetFillColor(SR,SG,SB);
        $this->SetFont('Arial','B',8); $this->SetTextColor(MR,MG,MB);
        $this->Cell($lw,6.5,$label,0,0,'L',true);
        $this->SetFont('Arial','',9); $this->SetTextColor(DR,DG,DB);
        $this->Cell(190-$lw,6.5,$val,0,1,'L',true);
    }

    public function plainRow(string $label, string $val, float $lw=52): void {
        $this->SetFont('Arial','B',8); $this->SetTextColor(MR,MG,MB);
        $this->Cell($lw,6,$label,0,0,'L');
        $this->SetFont('Arial','',9); $this->SetTextColor(DR,DG,DB);
        $this->Cell(0,6,$val,0,1,'L');
    }

    public function checkRow(string $label, bool $checked): void {
        $bx = $this->GetX()+2; $by = $this->GetY()+1.5;
        $this->SetDrawColor(TR,TG,TB); $this->SetLineWidth(0.35);
        $this->Rect($bx,$by,4,4);
        if ($checked) {
            $this->SetFont('Arial','B',11); $this->SetTextColor(TR,TG,TB);
            $this->SetXY($bx-0.5,$by-1.5); $this->Cell(5,6,'x',0,0,'C');
        }
        $this->SetFont('Arial','',9); $this->SetTextColor(DR,DG,DB);
        $this->SetXY($this->GetX()+9,$this->GetY());
        $this->Cell(0,6,$label,0,1,'L');
        $this->SetDrawColor(200,210,215); $this->SetLineWidth(0.2);
    }

    public function subHead(string $t): void {
        $this->SetFont('Arial','B',8.5); $this->SetTextColor(MR,MG,MB);
        $this->Cell(0,6,$t,0,1); $this->SetTextColor(DR,DG,DB);
    }

    public function para(string $t): void {
        $this->SetFont('Arial','',9); $this->SetTextColor(DR,DG,DB);
        $this->MultiCell(0,5.5,$t,0,'L'); $this->Ln(1);
    }
}

/* BUILD */
$pdf = new DisabilityReport('P','mm','A4');
$pdf->SetMargins(10,10,10);
$pdf->SetAutoPageBreak(true,18);
$pdf->SetCreator('ApexCare HMS');
$pdf->SetTitle('Disability Assessment — '.$a['patient_first'].' '.$a['patient_last']);
$pdf->AddPage();

$ref     = 'AC-DA-'.str_pad($assessment_id,6,'0',STR_PAD_LEFT);
$dateStr = date('d / m / Y', strtotime($a['assessment_date']));
$dobFmt  = $a['date_of_birth'] ? date('d / m / Y', strtotime($a['date_of_birth'])) : 'N/A';
$age     = $a['date_of_birth'] ? calcAge($a['date_of_birth']) : 'N/A';
$disType = strtolower(trim($a['disability_type'] ?? ''));

/* Reference bar */
$pdf->SetFillColor(SR,SG,SB); $pdf->SetFont('Arial','',8); $pdf->SetTextColor(MR,MG,MB);
$pdf->Cell(95,6,'Report Reference: '.$ref,0,0,'L',true);
$pdf->Cell(95,6,'Date of Assessment: '.$dateStr,0,1,'R',true);
$pdf->Ln(4);

/* S1 — Patient */
$pdf->sectionBar('1. Patient Identification');
$pdf->dataRow('Full Name',    safe($a['patient_first'].' '.$a['patient_last']));
$pdf->dataRow('National ID',  safe($a['national_id']));
$pdf->dataRow('Date of Birth',$dobFmt.'   (Age: '.$age.')');
$pdf->dataRow('Gender',       ucfirst(safe($a['gender'])));
$pdf->dataRow('Phone',        safe($a['phone']));
$pdf->dataRow('Email',        safe($a['email']));
$pdf->Ln(4);

/* S2 — Condition */
$pdf->sectionBar('2. Condition & Diagnosis');
$pdf->dataRow('Condition',      safe($a['condition_name']));
$pdf->dataRow('Category',       ucfirst(safe($a['condition_category'])));
$pdf->dataRow('Assessed By',    'Dr. '.safe($a['doctor_name']));
$pdf->dataRow('Specialization', safe($a['doctor_specialization'],'General Practice'));
$pdf->Ln(4);

/* S3 — Disability type checkboxes */
$pdf->sectionBar('3. Type of Disability');
$types = ['Physical Impairment','Visual Impairment','Hearing Impairment',
          'Speech/Communication Impairment','Intellectual Disability',
          'Mental Health Condition','Multiple Disabilities'];
$matched = false;
foreach ($types as $t) {
    $m = strtolower($t) === $disType;
    if ($m) $matched = true;
    $pdf->checkRow($t, $m);
}
if (!$matched && !empty($a['disability_type']))
    $pdf->checkRow('Other: '.$a['disability_type'], true);
else
    $pdf->checkRow('Other (specify)', false);
$pdf->Ln(3);

/* S4 — Functional assessment */
$pdf->sectionBar('4. Functional Assessment');
$pdf->subHead('Mobility Status:');
foreach (['Independent','Requires Assistive Device','Requires Personal Assistance','Wheelchair Dependent'] as $o)
    $pdf->checkRow($o, strtolower(safe($a['mobility_status'],'')) === strtolower($o));
$pdf->Ln(2);
$pdf->subHead('Self-Care Ability:');
foreach (['Fully Independent','Partially Dependent','Fully Dependent'] as $o)
    $pdf->checkRow($o, strtolower(safe($a['self_care_status'],'')) === strtolower($o));
$pdf->Ln(2);
$pdf->subHead('Communication Ability:');
foreach (['Normal','Impaired','Requires Aid / Assistive Technology'] as $o)
    $pdf->checkRow($o, str_starts_with(strtolower(safe($a['communication_status'],'')), strtolower(explode('/',$o)[0])));
$pdf->Ln(3);

/* S5 — Degree of impairment */
$pdf->sectionBar('5. Degree of Impairment');
$sev = (int)($a['severity_percentage'] ?? 0);
$pdf->plainRow('Estimated Impairment Level', $sev.'%');
$barY = $pdf->GetY();
$pdf->SetFillColor(220,232,237); $pdf->Rect(10,$barY,190,5,'F');
if ($sev > 0) { $pdf->SetFillColor(TR,TG,TB); $pdf->Rect(10,$barY,(190*$sev/100),5,'F'); }
$pdf->SetDrawColor(TR,TG,TB); $pdf->SetLineWidth(0.3); $pdf->Rect(10,$barY,190,5,'D');
$pdf->Ln(9);
$pdf->subHead('The condition is:');
foreach (['Temporary','Permanent','Progressive'] as $o)
    $pdf->checkRow($o, strtolower(safe($a['permanence'],'')) === strtolower($o));
$pdf->Ln(2);
$pdf->subHead('Prognosis:');
foreach (['Likely to Improve'=>'improving','Stable'=>'stable','Likely to Deteriorate'=>'deteriorating'] as $l=>$k)
    $pdf->checkRow($l, ($a['prognosis']??'') === $k);
$pdf->Ln(3);

/* S6 — Clinical findings */
$pdf->sectionBar('6. Clinical Examination Findings');
$pdf->para(safe($a['clinical_findings'],'No clinical findings recorded.'));
$pdf->Ln(2);

/* S7 — Recommendations */
$pdf->sectionBar('7. Recommendations');
$pdf->para(safe($a['recommendations'],'No recommendations recorded.'));
$pdf->Ln(2);

/* S8 — Certification */
$pdf->sectionBar('8. Certification by Medical Practitioner');
$pdf->SetFont('Arial','I',9); $pdf->SetTextColor(MR,MG,MB);
$pdf->MultiCell(0,5.5,'I hereby certify that the above-named patient has been medically examined and assessed in accordance with professional medical standards. The findings documented herein reflect my independent clinical judgment.',0,'L');
$pdf->Ln(3);
$pdf->plainRow("Doctor's Full Name",  'Dr. '.safe($a['doctor_name']));
$pdf->plainRow('Medical Designation', safe($a['doctor_specialization'],'Medical Practitioner'));
$pdf->plainRow('Date',                $dateStr);
$pdf->Ln(8);
$sigY = $pdf->GetY();
$pdf->SetDrawColor(TR,TG,TB); $pdf->SetLineWidth(0.4);
$pdf->Line(10,$sigY,95,$sigY);
$pdf->SetFont('Arial','',8); $pdf->SetTextColor(MR,MG,MB);
$pdf->SetXY(10,$sigY+2); $pdf->Cell(85,5,'Doctor Signature & Official Stamp',0,0,'L');
$pdf->Ln(12);

/* Verification bar */
$vc = strtoupper(substr(hash('sha256',$assessment_id.$patient_id.$a['assessment_date']),0,16));
$pdf->SetFillColor(NR,NG,NB); $pdf->SetTextColor(WR,WG,WB); $pdf->SetFont('Arial','',8);
$pdf->Cell(130,7,'  Electronically generated · ApexCare Health Management System',0,0,'L',true);
$pdf->Cell(60, 7,'Verification: '.$vc,0,1,'C',true);

/* SAVE */
$dir   = __DIR__.'../pdf_reports/';
$file  = 'disability_'.$patient_id.'_'.$assessment_id.'.pdf';
$path  = $dir.$file;
$wpath = 'pdf_reports/'.$file;
if (!is_dir($dir)) mkdir($dir,0755,true);
$pdf->Output('F',$path);

/* UPDATE DB */
$conn->prepare("UPDATE disability_assessments SET pdf_path=:p WHERE id=:id AND patient_id=:pid")
     ->execute([':p'=>$wpath,':id'=>$assessment_id,':pid'=>$patient_id]);

/* STREAM */
$dlName = 'ApexCare_Disability_'.str_replace(' ','_',$a['patient_first'].'_'.$a['patient_last']).'_'.date('Ymd',strtotime($a['assessment_date'])).'.pdf';
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="'.$dlName.'"');
header('Content-Length: '.filesize($path));
header('Cache-Control: private, max-age=0, must-revalidate');
readfile($path);
exit();
